# Asset pricing

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import scipy.stats

pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns', 50)

## FM regression

In [2]:
data = pd.read_csv('input/FamaFrench.csv')
data.head()

date  VWMe   SMB   HML    RF  S1V1   S1V2  S1V3  S1V4  S1V5  S2V1  S2V2  \
0  192607  2.62 -2.16 -2.92  0.22  3.61  -3.69 -0.64 -1.42 -0.64  3.42  3.26   
1  192608  2.56 -1.49  4.88  0.25 -1.94  -6.78  3.81  1.21  4.82  1.59 -2.91   
2  192609  0.36 -1.38 -0.01  0.23 -6.41   3.45 -5.19  3.08  0.75 -2.81 -2.32   
3  192610 -3.43  0.04  0.71  0.32 -8.66 -10.02 -3.80  0.04 -3.06 -3.65 -3.77   
4  192611  2.44 -0.24 -0.31  0.31  3.77  12.42  2.31 -3.36  1.40  1.50 -2.77   

   S2V3  S2V4  S2V5  S3V1  S3V2  S3V3  S3V4  S3V5  S4V1  S4V2  S4V3  S4V4  \
0  2.42 -1.27  2.46  1.56  2.86 -1.34  3.34 -2.16  3.29  1.24  1.29  0.55   
1  3.02  2.14  7.47 -1.06  1.67  2.08  4.86  8.14  0.76  4.11  1.93  2.13   
2  1.15 -1.54 -2.61 -0.46  1.25 -2.37  1.01 -2.74  1.87 -0.08 -1.84  1.56   
3 -7.02 -6.29  0.08 -4.80 -2.23 -0.05 -1.73 -3.73  0.13 -1.71 -2.33 -2.93   
4  4.03  3.46  1.62  1.78  4.64  3.27  3.54  3.40  3.54  2.28  3.85  5.00   

   S4V5  S5V1  S5V2  S5V3  S5V4  S5V5  
0  2.56  3.18  6.08  2.00  2.93  0.56  
1  4.47  1.17  4.10  1.82  5.64  7.76  
2  2.18 -1.37  3.66 -0.23 -0.30 -2.43  
3 -5.21 -3.14 -3.13 -2.21 -4.59 -5.81  
4  1.78  4.31  2.61  1.47  3.55  2.56

In [3]:
# get only values
dates = data['date'].values
factors = data[['VWMe', 'SMB', 'HML']].values
riskfree = data['RF'].values
portfolios = data.iloc[:, 5:].values

# convert to matrix
factors = np.mat(factors)
riskfree = np.mat(riskfree)
portfolios = np.mat(portfolios)

T,K = factors.shape
N = portfolios.shape[1]
# inverse
riskfree = riskfree.T
# subtruct riskfree rate from every columns
excessReturns = portfolios - riskfree

# add 1s to first column
X = sm.add_constant(factors)

# run OLS
# Y is all 25 porfolio excess return, T=1026, shape is (1026,25)
# X first column is constant, VWMe, SMB, HML shape is (1026,4)
# every column of Y regress on X, therefore
# Y = X * beta, producing beta of shape (4,25)
ts_res = sm.OLS(excessReturns, X).fit()

In [18]:
excessReturns

matrix([[ 3.39, -3.91, -0.86, ...,  1.78,  2.71,  0.34],
        [-2.19, -7.03,  3.56, ...,  1.57,  5.39,  7.51],
        [-6.64,  3.22, -5.42, ..., -0.46, -0.53, -2.66],
        ...,
        [13.67, 15.05, 14.95, ..., 12.82,  9.16, 12.72],
        [-1.85, -1.16, -3.15, ...,  0.84,  0.72, -4.46],
        [-0.05,  2.02,  1.55, ...,  2.74,  3.2 ,  0.61]])

In [19]:
excessReturns[:,0]

matrix([[ 3.39],
        [-2.19],
        [-6.64],
        ...,
        [13.67],
        [-1.85],
        [-0.05]])

In [20]:
test_res0 = sm.OLS(excessReturns[:,0], X).fit()

In [21]:
test_res0.params

array([-0.83535616,  1.30989756,  1.28916295,  0.39425156])

In [24]:
ts_res.params[:,0]

array([-0.83535616,  1.30989756,  1.28916295,  0.39425156])

In [12]:
pd.DataFrame(ts_res.params)

0         1         2         3         4         5         6   \
0 -0.835356 -0.391107 -0.121852  0.038833  0.091779 -0.239747 -0.019438   
1  1.309898  1.085291  1.074662  0.963022  0.984967  1.069092  1.041550   
2  1.289163  1.610011  1.181175  1.224859  1.345308  1.051988  0.988023   
3  0.394252  0.331737  0.464803  0.585383  0.905162 -0.264721  0.187710   

         7         8         9         10        11        12        13  \
0  0.089810  0.048150 -0.010901 -0.155604  0.088897  0.111762  0.081767   
1  0.959023  0.978756  1.050202  1.141644  1.013270  1.012869  0.961480   
2  0.861899  0.817789  0.937324  0.788300  0.515121  0.412995  0.464647   
3  0.355321  0.556241  0.849301 -0.198041  0.072006  0.337946  0.506756   

         14        15        16        17        18        19        20  \
0 -0.052555  0.090232 -0.010430  0.039223  0.014802 -0.176172  0.079394   
1  1.144679  1.066124  1.030785  1.009604  1.043655  1.228421  1.031042   
2  0.497000  0.285666  0.243002  0.221419  0.201554  0.297373 -0.150711   
3  0.914274 -0.369234  0.132789  0.297967  0.585687  0.983352 -0.250803   

         21        22        23        24  
0  0.053454 -0.023604 -0.197831 -1.273695  
1  0.957574  0.975277  1.054550  1.104513  
2 -0.189343 -0.217260 -0.173163  0.007600  
3 -0.010672  0.312715  0.711547  0.852679

In [31]:
# first row of params is constant coefficient
# therefore alpha of 25 porfolio, shape is (25,), 1d-array
alpha = ts_res.params[0]
# shape is (3,25)
beta = ts_res.params[1:]

## not FM REG, CS REG
- CS reg: avg then reg
- FM reg: reg then avg 

In [36]:
excessReturns.shape

(1026, 25)

In [35]:
avgExcessReturns.shape

(1, 25)

In [33]:
# column-wise mean, shape (25)
avgExcessReturns = np.mean(excessReturns, 0)
# corss-section regression
# reshape avgExcessReturns to column vector (25,1)
# reshape beta to (25,3)
cs_res = sm.OLS(avgExcessReturns.T, beta.T).fit()
# producing risk premia of (3,), 1d-array
riskPremia = cs_res.params

In [40]:
fm_res = sm.OLS(excessReturns.T, beta.T).fit()

In [42]:
pd.DataFrame(fm_res.params)

0         1         2         3         4         5         6     \
0  2.902191  1.982859 -0.375685 -2.897510  2.659893  2.126554  0.131271   
1 -1.733590 -3.085720 -0.612406 -1.326576  0.040849  0.111386 -1.786543   
2 -2.272799  5.113520 -0.184279 -0.406083 -0.648074  0.172236  4.260242   

       7         8         9         10        11        12        13    \
0  3.724361 -0.162132 -0.838004  3.754173 -1.461314  6.175553  1.849327   
1  0.648455 -1.273525  1.757246  2.587442  2.313589  2.499903  0.180572   
2  4.229522 -1.084203  2.549532  3.540680 -2.873203 -1.098447 -3.322965   

       14        15        16        17        18        19        20    \
0  4.372585 -2.253312  6.820539  2.689874 -0.613849 -2.379983  9.864428   
1 -3.554234  0.057927  2.714133 -2.030487  3.592304 -0.016965  0.153157   
2  0.868620 -7.266533 -0.310948  2.333917 -1.312081 -1.100756 -2.120518   

       21        22        23        24    ...      1001      1002      1003  \
0  2.759236  0.774133 -4.802539  0.242596  ...  3.638713 -3.451801  3.706138   
1  3.881477  5.684518 -3.886247 -0.800151  ...  4.319951  0.181803  0.009290   
2  1.602814 -2.513432 -0.947060  0.070132  ...  0.182974  1.116048  2.230679   

       1004      1005      1006      1007      1008      1009       1010  \
0  6.381665  1.434721 -6.754378 -4.951884  6.828315 -4.008476  10.007383   
1  0.917463  3.977628  0.728991 -0.715964 -0.874400 -2.703675   2.954092   
2  1.305584  2.957860 -3.045393 -4.807109  0.584958 -1.649656  -3.168021   

       1011      1012      1013      1014      1015      1016      1017  \
0  3.568753  1.492150  6.331637  2.474398  3.773448  1.253090  3.290954   
1  1.046076  2.750212  0.556224 -2.453806  1.310708  2.084922 -0.594494   
2 -1.678490 -1.721987  2.801298 -0.253351 -0.107456 -1.319883 -2.035969   

       1018      1019      1020      1021      1022       1023      1024  \
0 -0.803361 -1.580124 -3.054333 -6.065619 -8.106962  12.775805  0.002666   
1 -0.365005 -0.234231 -0.295486 -2.961944 -2.281100   1.803807 -0.527685   
2 -1.320858 -0.197748 -0.118441 -0.808509 -0.542449  -2.256583 -0.080628   

       1025  
0 -0.059588  
1 -0.066462  
2  2.131815  

[3 rows x 1026 columns]

In [43]:
pd.DataFrame(fm_res.resid)

0         1         2         3         4          5         6     \
0   2.719363 -2.825359 -5.285747 -3.314288  0.178655  10.372933  0.571587   
1  -3.514649 -5.910276  4.674841 -4.924845  9.372465  -5.124399 -6.739391   
2  -0.874797  2.697094 -4.207253  0.749510 -0.605510  -3.776949 -2.461024   
3  -0.981013 -0.163331  4.069778  4.372948 -5.902199   2.654825  4.147975   
4   0.670901  2.139631  1.880715  1.626176 -0.998250  -0.530336 -0.202054   
5   1.319351  3.819939 -2.042897  0.415747 -1.868201   2.004937  2.676856   
6   2.156676 -3.136343 -1.519043  0.314814 -5.769122   1.872706 -4.611269   
7   1.718485  1.711031  1.873601 -3.273557  1.364167   0.333383 -1.749825   
8  -1.648603 -0.371616 -0.798973 -2.463305  0.873692  -1.838273 -1.537187   
9   2.747341  3.686999 -1.714923  4.391289 -0.971304   0.616004  9.018480   
10 -1.056787 -0.128558  0.185164 -0.846756 -1.727198  -4.071463  2.132171   
11  0.755962  0.632146  1.729403  1.098546  1.660434  -0.484552 -0.149489   
12 -3.015491 -0.632082 -1.904284  3.249900  0.468021  -3.208128 -0.754858   
13  2.286864  1.545982  1.519151  1.558072  0.982000   0.706324  0.794993   
14 -2.762520  2.478710 -2.067114  0.297296  0.617492  -2.057050 -0.857378   
15 -0.368062  1.165595  2.147428  3.128123  0.143264   0.004606  4.543428   
16 -1.248464  1.886916  0.250537  1.332994 -0.695647  -0.211958  1.133108   
17 -0.798994 -1.162328 -1.500199  0.690067  1.038620  -0.262962 -1.986370   
18 -1.018326 -2.562404  1.953448  0.279216  2.285323   0.077284 -2.012085   
19  1.525372 -2.326562  2.774824 -1.176828 -1.172332  -1.294795  3.530699   
20 -0.863575 -0.306974 -1.351167 -0.774322  1.101156  -0.892582 -0.456115   
21  2.728437  1.421578  3.671824 -0.930931 -0.246228   1.176595 -0.358505   
22 -0.716343 -2.633316 -0.169028  0.134651 -1.222596  -0.313641 -2.538412   
23  0.966504 -0.873864 -0.108744 -1.795197  0.903217   3.124176 -3.239155   
24 -0.914362  0.983165 -2.083266 -2.573323 -0.135597  -0.366515  0.205967   

        7         8         9         10        11         12         13    \
0  -5.201992  8.261606  3.297167 -0.869135 -4.385658  12.740940  10.804868   
1   0.250878  0.336020  1.064519  3.325247  5.414192  17.927253  -3.785431   
2   3.755738 -3.917567  1.589927 -8.556406 -6.176863  -6.158893   1.343834   
3  -2.066797 -3.439301  1.632187  5.952744  2.115380  -4.976211  -1.796913   
4   0.820853 -0.625643  1.803631  1.236468 -4.022431  -3.661584   1.133369   
5  -3.104208 -0.853944 -2.137784  0.361779  3.737813  -4.112883  -3.916718   
6   2.096281  0.320655 -6.311947 -4.461230  3.225481  -5.065919   2.599176   
7   1.926511  1.428378 -3.696805 -2.938530  3.988263  -0.746861  -6.578464   
8  -2.508174 -0.696760  0.534992  0.380128 -0.713565  -1.257753  -0.379342   
9  -0.571283  1.154792  0.897644  2.624984 -4.223694  -3.915885   6.550777   
10  2.194547  1.384300 -2.823622 -1.174410 -1.774515  -7.078495  -2.161702   
11  0.437635 -3.281628  0.580349  1.008215 -3.544187  -2.166158  -0.117611   
12 -0.099447  0.026579 -1.358549 -0.857643 -0.394394  -1.666255   2.075281   
13  0.644461 -1.292947  0.917234  1.433928  2.036036  -3.782598  -2.558060   
14  4.917581 -4.480211 -1.465076  4.039569  5.859775   0.072807  -4.948530   
15  2.475809 -2.203669  1.582805  1.795780  0.266145  -1.443627  -1.260146   
16 -1.218226 -0.209437  1.628237 -0.198664 -1.774377  -0.287288   1.641116   
17 -2.473971  0.188729 -1.292713 -1.938146 -1.290803   0.778911  -0.156935   
18 -0.534824 -1.049103 -0.922820  0.456698  0.021592   0.544332  -3.130238   
19  2.072977  6.744031  4.249778 -1.972874  3.702477  -5.319423  -5.627807   
20  0.468534  0.043309  4.188283  2.677258  0.754750   4.484014   4.157070   
21  1.421567  1.582549  1.772384  1.392802 -1.563284   0.118066  -0.552142   
22 -1.714036 -0.529517 -0.448210  1.013565 -0.193669   1.143755  -0.895235   
23 -2.104739  1.141910 -1.056104 -0.930275  0.626074   3.112056   1.175505   
24 -1.714958 -3.026767 -5.041702 -2.715262 -1.573622   

In [38]:
cs_res.resid.shape

(25,)

## GMM