In [1]:
from finance_byu.fama_macbeth import fama_macbeth, fm_summary
import statsmodels.api as sm
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('ff_data.csv')
data['month'] = data['month'].astype(str)
data

month       SL       SM       SH       BL      BM       BH  mkt-rf   smb  \
0  202201 -13.3312  -9.0569  -1.0018  -7.9554 -2.8507   5.2226   -6.25 -5.94   
1  202202   0.0517   1.2208   2.2370  -3.5601  0.0278   0.3395   -2.29  2.23   
2  202203   1.7806   1.0372   0.5629   4.3278  1.9104   1.9377    3.05 -1.60   
3  202204 -13.5805  -8.5466  -5.5740 -10.5954 -6.6579  -6.2179   -9.46 -1.41   
4  202205  -4.4206   1.6393   4.1352  -2.6261  3.8821   5.6393   -0.34 -1.85   
5  202206  -4.3163  -6.6654 -11.2053  -7.2567 -8.9137 -12.2993   -8.43  2.09   
6  202207  13.4122  10.8013   8.6857  11.4381  5.1174   7.9978    9.56  2.78   

     hml  
0  12.75  
1   3.04  
2  -1.80  
3   6.19  
4   8.41  
5  -5.97  
6  -4.08

In [3]:
unstack = data.drop(columns=['mkt-rf','smb','hml'])
unstack = pd.DataFrame(unstack.set_index('month').unstack()).reset_index()
unstack.columns = ['port','month','ret']

In [40]:
test = pd.merge(unstack, data[['month','mkt-rf','smb','hml']], how='left', on='month')
test

port   month      ret  mkt-rf   smb    hml
0    SL  202201 -13.3312   -6.25 -5.94  12.75
1    SL  202202   0.0517   -2.29  2.23   3.04
2    SL  202203   1.7806    3.05 -1.60  -1.80
3    SL  202204 -13.5805   -9.46 -1.41   6.19
4    SL  202205  -4.4206   -0.34 -1.85   8.41
5    SL  202206  -4.3163   -8.43  2.09  -5.97
6    SL  202207  13.4122    9.56  2.78  -4.08
7    SM  202201  -9.0569   -6.25 -5.94  12.75
8    SM  202202   1.2208   -2.29  2.23   3.04
9    SM  202203   1.0372    3.05 -1.60  -1.80
10   SM  202204  -8.5466   -9.46 -1.41   6.19
11   SM  202205   1.6393   -0.34 -1.85   8.41
12   SM  202206  -6.6654   -8.43  2.09  -5.97
13   SM  202207  10.8013    9.56  2.78  -4.08
14   SH  202201  -1.0018   -6.25 -5.94  12.75
15   SH  202202   2.2370   -2.29  2.23   3.04
16   SH  202203   0.5629    3.05 -1.60  -1.80
17   SH  202204  -5.5740   -9.46 -1.41   6.19
18   SH  202205   4.1352   -0.34 -1.85   8.41
19   SH  202206 -11.2053   -8.43  2.09  -5.97
20   SH  202207   8.6857    9.56  2.78  -4.08
21   BL  202201  -7.9554   -6.25 -5.94  12.75
22   BL  202202  -3.5601   -2.29  2.23   3.04
23   BL  202203   4.3278    3.05 -1.60  -1.80
24   BL  202204 -10.5954   -9.46 -1.41   6.19
25   BL  202205  -2.6261   -0.34 -1.85   8.41
26   BL  202206  -7.2567   -8.43  2.09  -5.97
27   BL  202207  11.4381    9.56  2.78  -4.08
28   BM  202201  -2.8507   -6.25 -5.94  12.75
29   BM  202202   0.0278   -2.29  2.23   3.04
30   BM  202203   1.9104    3.05 -1.60  -1.80
31   BM  202204  -6.6579   -9.46 -1.41   6.19
32   BM  202205   3.8821   -0.34 -1.85   8.41
33   BM  202206  -8.9137   -8.43  2.09  -5.97
34   BM  202207   5.1174    9.56  2.78  -4.08
35   BH  202201   5.2226   -6.25 -5.94  12.75
36   BH  202202   0.3395   -2.29  2.23   3.04
37   BH  202203   1.9377    3.05 -1.60  -1.80
38   BH  202204  -6.2179   -9.46 -1.41   6.19
39   BH  202205   5.6393   -0.34 -1.85   8.41
40   BH  202206 -12.2993   -8.43  2.09  -5.97
41   BH  202207   7.9978    9.56  2.78  -4.08

# byu-finance


In [41]:
result = fama_macbeth(test,'month','ret',['mkt-rf','smb','hml'],intercept=True)
fm_summary(result)

mean  std_error     tstat
intercept  0.008804   0.027242  0.323186
mkt-rf     0.359346   0.123803  2.902573
smb        0.009087   0.057107  0.159119
hml       -0.085871   0.115726 -0.742019

In [38]:
result

intercept    mkt-rf       smb       hml
month                                          
202201  -0.020297  0.126858  0.120566 -0.258790
202202   0.002580 -0.005908  0.005753  0.007843
202203   0.119615  0.364826 -0.191384 -0.215307
202204  -0.065206  0.616852  0.091941 -0.403627
202205   0.018267 -0.006211 -0.033793  0.153623
202206  -0.075332  0.635051 -0.157444  0.449734
202207   0.082003  0.783953  0.227970 -0.334574

# np.linalg.lstsq

In [9]:
X = np.array([np.ones(9), np.arange(0, 9)]).T
y = np.array([19, 20, 20.5, 21.5, 22, 23, 23, 25.5, 24])

In [10]:
# 9 row, 2 column
X

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.]])

In [11]:
y # 默认为列向量，显示为行

array([19. , 20. , 20.5, 21.5, 22. , 23. , 23. , 25.5, 24. ])

In [12]:
y.shape

(9,)

In [13]:
w = np.linalg.lstsq(X, y, rcond=None)[0]
w

array([19.18888889,  0.71666667])

# statsmodels

In [14]:
res = sm.OLS(y, X).fit()
res.summary()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     74.24
Date:                Sat, 17 Sep 2022   Prob (F-statistic):           5.66e-05
Time:                        22:22:57   Log-Likelihood:                -7.6827
No. Observations:                   9   AIC:                             19.37
Df Residuals:                       7   BIC:                             19.76
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         19.1889      0.396     48.458      0.000      18.253      20.125
x1             0.7167      0.083      8.616      0.000       0.520       0.913
==============================================================================
Omnibus:                        4.624   Durbin-Watson:                   3.078
Prob(Omnibus):                  0.099   Jarque-Bera (JB):                1.154
Skew:                           0.773   Prob(JB):                        0.561
Kurtosis:                       3.830   Cond. No.                         9.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
res.params

array([19.18888889,  0.71666667])

In [16]:
res.resid

array([-0.18888889,  0.09444444, -0.12222222,  0.16111111, -0.05555556,
        0.22777778, -0.48888889,  1.29444444, -0.92222222])

# direct compute
回归方程
$$
y = X \beta + \varepsilon
$$
都为列向量
$$
\hat{\beta} = (X^T X)^{-1} X^T y
$$

In [17]:
from numpy import dot
from numpy.linalg import inv
from scipy import stats

In [18]:
dot(inv(dot(X.T, X)),dot(X.T,y))

array([19.18888889,  0.71666667])

In [19]:
dot(dot(inv(dot(X.T, X)),X.T),y)

array([19.18888889,  0.71666667])

In [20]:
np.matmul(np.matmul(inv(np.matmul(X.T,X)),X.T),y)

array([19.18888889,  0.71666667])

In [21]:
# 列向量显示的时候，并不会专门显示为列
(inv(X.T @ X) @ X.T @ y).shape

(2,)

In [22]:
inv(X.T @ X) @ X.T @ y

array([19.18888889,  0.71666667])

In [23]:
beta_hat = inv(X.T @ X) @ X.T @ y

 ## se of coefficient 计算

In [24]:
epsilon = y - X @ beta_hat
epsilon

array([-0.18888889,  0.09444444, -0.12222222,  0.16111111, -0.05555556,
        0.22777778, -0.48888889,  1.29444444, -0.92222222])

In [25]:
sse = np.square(epsilon).sum()
mse = sse / (9-2) #减去两个dof

In [26]:
mse

0.41507936507936505

In [27]:
np.sqrt(mse)

0.6442665326395319

In [28]:
epsilon.std(ddof=2)

0.6442665326395319

In [29]:
# MSE 即为\sigma^2
inv(X.T @ X)

array([[ 0.37777778, -0.06666667],
       [-0.06666667,  0.01666667]])

In [30]:
epsilon.std(ddof=2) * 0.37777778**0.5 

0.3959895971657489

In [31]:
epsilon.std(ddof=2) * 0.01666667**0.5

0.0831744600318349

In [32]:
mse * inv(X.T @ X)

array([[ 0.15680776, -0.02767196],
       [-0.02767196,  0.00691799]])

In [33]:
np.sqrt(0.15680776)

0.3959895958229206

In [34]:
np.sqrt(0.00691799)

0.08317445521312418

# byu code

In [35]:
def _ols_np(data,vars):
    #assert np.linalg.matrix_rank(data[vars[1]])==len(vars[1]), 'Independent variable matrix is not full column rank. Check data carefully.'
    gamma,_,_,_ = np.linalg.lstsq(data[vars[1]],data[vars[0]],rcond=None)
#     print(data[vars[1]],data[vars[0]])
    return pd.Series(gamma.flatten())

def fama_macbeth(data,t,yvar,xvar,intercept=True):

#     _assertions(data,t,yvar,xvar,intercept)
    
    if intercept:
        data['intercept'] = 1
        xvar.insert(0,'intercept')
    d = (data.groupby(t).apply(_ols_np,[yvar,xvar]))
    d.columns = xvar
    return d